### ISSUE TITLE
Requesting access to all org units on dip report

### ISSUE THREAD

**Issue by sagunkc-hki** [hispindia/DHIS2-HKI#11]
Please grant access to all org units for Ktm center users in DIP report. Urgent.

**Comment by Saurabhhisp** [comment]
@sagunkc-hki 

The DIP report picks the same organisation units as assigned to the respective user.

Right now KTM centre uses have only KTM centre assigned as their org unit.

In order to show them all organisation units in the report they will have to be assigned Suaahara II as their organisation unit.

Please confirm!

**Comment by Saurabhhisp** [comment]
@sagunkc-hki 

Please confirm if this is required!

**Comment by sagunkc-hki** [comment]
This is not required for now. We will plan overall authorization system to move forward.
